* Encoding: UTF-8.

DESCRIPTIVES VARIABLES=sw covert overt
  /STATISTICS=MEAN STDDEV MIN MAX.


CORRELATIONS
  /VARIABLES=sw covert overt
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.


REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF R
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN 
  /DEPENDENT sw
  /METHOD=ENTER covert overt
  /SCATTERPLOT=(sw , covert) (sw , overt).

